-- 外部キー制約を一時的に無効化
SET FOREIGN_KEY_CHECKS = 0;

-- MCテーブルにデータを挿入
INSERT INTO `MC` (`name`, `createdAt`, `updatedAt`) VALUES
('R-指定', NOW(), NOW()),
('T-Pablow', NOW(), NOW()),
('FORK', NOW(), NOW()),
('MOL53', NOW(), NOW()),
('般若', NOW(), NOW()),
('鎮座DOPENESS', NOW(), NOW()),
('チプルソ', NOW(), NOW()),
('Authority', NOW(), NOW()),
('呂布カルマ', NOW(), NOW()),
('輪入道', NOW(), NOW()),
('紅桜', NOW(), NOW()),
('黄猿', NOW(), NOW()),
('SILENT KILLA JOINT', NOW(), NOW()),
('SAM', NOW(), NOW()),
('GADORO', NOW(), NOW()),
('CHICO CARLITO', NOW(), NOW()),
('Benjazzy', NOW(), NOW()),
('晋平太', NOW(), NOW()),
('スナフキン', NOW(), NOW()),
('Bonbero', NOW(), NOW()),
('ACE', NOW(), NOW()),
('9for', NOW(), NOW()),
('TERU', NOW(), NOW()),
('SKRYU', NOW(), NOW()),
('Red Eye', NOW(), NOW()),
('MCニガリ', NOW(), NOW()),
('Lick-G', NOW(), NOW()),
('CIMA', NOW(), NOW()),
('Sitissy luvit', NOW(), NOW()),
('孫GONG', NOW(), NOW()),
('裂固', NOW(), NOW()),
('ZEEBRA', NOW(), NOW()),
('Yella goat', NOW(), NOW()),
('S-kaine', NOW(), NOW()),
('OZworld a.k.a. R''kuma', NOW(), NOW()),
('MU-TON', NOW(), NOW()),
('ERONE', NOW(), NOW()),
('DOTAMA', NOW(), NOW()),
('CHEHON', NOW(), NOW()),
('梵頭', NOW(), NOW()),
('焚巻', NOW(), NOW()),
('SIMON JAP', NOW(), NOW()),
('Scooby J', NOW(), NOW()),
('KZ', NOW(), NOW()),
('GIL', NOW(), NOW()),
('BALA aka SBKN', NOW(), NOW()),
('言xTHEANSWER', NOW(), NOW()),
('ミメイ', NOW(), NOW()),
('ふぁんく', NOW(), NOW()),
('Rin音', NOW(), NOW()),
('Ray', NOW(), NOW()),
('koperu', NOW(), NOW()),
('K-rush', NOW(), NOW()),
('GOMESS', NOW(), NOW()),
('Fuma no KTR', NOW(), NOW()),
('T-TANGG', NOW(), NOW()),
('句潤', NOW(), NOW()),
('龍鬼', NOW(), NOW()),
('早雲', NOW(), NOW()),
('写楽', NOW(), NOW()),
('漢 a.k.a. GAMI', NOW(), NOW()),
('ドイケン（KennyDoes）', NOW(), NOW()),
('TKda黒ぶち', NOW(), NOW()),
('SHOHEI', NOW(), NOW()),
('Rude-α', NOW(), NOW()),
('peko', NOW(), NOW()),
('Novel Core', NOW(), NOW()),
('KOOPA', NOW(), NOW()),
('ID', NOW(), NOW()),
('BATTLE手裏剣', NOW(), NOW()),
('Base', NOW(), NOW()),
('Red wing', NOW(), NOW()),
('RAGA', NOW(), NOW()),
('MC frog', NOW(), NOW()),
('MAVEL', NOW(), NOW()),
('KEN THE 390', NOW(), NOW()),
('KBD', NOW(), NOW()),
('JUMBO MAATCH', NOW(), NOW()),
('HIDADDY', NOW(), NOW()),
('11''Back', NOW(), NOW()),
('歩歩', NOW(), NOW()),
('左流', NOW(), NOW()),
('歌々詩（ex.よんろく）', NOW(), NOW()),
('ゆうま', NOW(), NOW()),
('ハハノシキュウ', NOW(), NOW()),
('がーどまん', NOW(), NOW()),
('Ry-lax', NOW(), NOW()),
('Mr.Q', NOW(), NOW()),
('Jinmenusagi', NOW(), NOW()),
('HARDY', NOW(), NOW()),
('寿君', NOW(), NOW()),
('ブッダ', NOW(), NOW()),
('クボタカイ', NOW(), NOW()),
('かしわ', NOW(), NOW()),
('whimsyboy', NOW(), NOW()),
('TERA-Z', NOW(), NOW()),
('STACK THE PINK', NOW(), NOW()),
('Shamis', NOW(), NOW()),
('POWER WAVE', NOW(), NOW()),
('MAKA', NOW(), NOW()),
('Maiji', NOW(), NOW()),
('L.B.R.L', NOW(), NOW()),
('HYDRO', NOW(), NOW()),
('GOLBY', NOW(), NOW()),
('GOCCI', NOW(), NOW()),
('DOPEMAN', NOW(), NOW()),
('D.D.S', NOW(), NOW()),
('bunTes', NOW(), NOW()),
('掌幻', NOW(), NOW()),
('だーひー', NOW(), NOW()),
('しぇん', NOW(), NOW()),
('サイプレス上野', NOW(), NOW()),
('カルデラビスタ', NOW(), NOW()),
('SyAchi', NOW(), NOW()),
('ONO-D', NOW(), NOW()),
('lonelow', NOW(), NOW()),
('KUREI', NOW(), NOW()),
('K.Lee', NOW(), NOW()),
('Chance', NOW(), NOW()),
('Dragon One', NOW(), NOW()),
('煩悩', NOW(), NOW()),
('ミステリオ', NOW(), NOW()),
('アスベスト', NOW(), NOW()),
('MC龍', NOW(), NOW()),
('Keyser', NOW(), NOW()),
('K-razy', NOW(), NOW()),
('GOTIT', NOW(), NOW()),
('BIG MOOLA', NOW(), NOW()),
('狺-TARØET', NOW(), NOW()),
('百足', NOW(), NOW()),
('斑', NOW(), NOW()),
('智大', NOW(), NOW()),
('バチスタ', NOW(), NOW()),
('じょう', NOW(), NOW()),
('MC松島', NOW(), NOW()),
('Kampf', NOW(), NOW()),
('Itaq', NOW(), NOW()),
('Dr.マキダシ', NOW(), NOW()),
('DARTHREIDER', NOW(), NOW()),
('CJ', NOW(), NOW()),
('Charlu', NOW(), NOW()),
('''018', NOW(), NOW()),
('BOZ', NOW(), NOW()),
('鬼', NOW(), NOW()),
('韻マン', NOW(), NOW()),
('アマテラス', NOW(), NOW()),
('Y.A.S', NOW(), NOW()),
('RYKEY DADDY DIRTY', NOW(), NOW()),
('MK34', NOW(), NOW()),
('crap the grubby', NOW(), NOW()),
('MEGA-G', NOW(), NOW()),
('ツチヤチカら', NOW(), NOW()),
('OWG', NOW(), NOW()),
('APOLLO', NOW(), NOW()),
('椿', NOW(), NOW()),
('知葉瑠', NOW(), NOW()),
('脱走', NOW(), NOW()),
('溝上たんぼ', NOW(), NOW()),
('SHAMO', NOW(), NOW()),
('Nidra Assassin', NOW(), NOW()),
('NAIKA MC', NOW(), NOW()),
('KYO虎', NOW(), NOW()),
('Kenty Gross', NOW(), NOW()),
('SURGE', NOW(), NOW()),
('楓', NOW(), NOW()),
('杏地', NOW(), NOW()),
('ケツのアブノーマル', NOW(), NOW()),
('NONKEY', NOW(), NOW()),
('ARARE', NOW(), NOW()),
('崇勲', NOW(), NOW()),
('十六夜', NOW(), NOW()),
('Randy Wati Sati', NOW(), NOW()),
('K''iLL', NOW(), NOW()),
('ala vivere luce', NOW(), NOW()),
('NillNico', NOW(), NOW()),
('venom', NOW(), NOW()),
('SHJ', NOW(), NOW()),
('FRANKEN', NOW(), NOW()),
('Donatello', NOW(), NOW()),
('磯友', NOW(), NOW()),
('影賭', NOW(), NOW()),
('Joker clown', NOW(), NOW()),
('Felipe', NOW(), NOW()),
('Bass', NOW(), NOW()),
('9L!', NOW(), NOW()),
('鉄ちゃん', NOW(), NOW()),
('しーじん', NOW(), NOW()),
('オロカモノポテチ', NOW(), NOW()),
('Ryo', NOW(), NOW()),
('RunLine', NOW(), NOW()),
('SATORU', NOW(), NOW()),
('ベル', NOW(), NOW()),
('テトリス', NOW(), NOW()),
('EIEN', NOW(), NOW()),
('SHIEN', NOW(), NOW()),
('mogura', NOW(), NOW()),
('阿修羅', NOW(), NOW()),
('彼岸', NOW(), NOW()),
('佐藤アヴァンギャルドJK', NOW(), NOW()),
('ピラフ星人', NOW(), NOW()),
('ガチギレMC', NOW(), NOW()),
('#久保田', NOW(), NOW()),
('4-May', NOW(), NOW()),
('MY', NOW(), NOW()),
('shoichiro', NOW(), NOW()),
('札幌のギャグ男', NOW(), NOW()),
('あちち', NOW(), NOW()),
('MIRI', NOW(), NOW()),
('天涯孤独の民', NOW(), NOW()),
('瀧澤彩夏', NOW(), NOW()),
('はまちゅー', NOW(), NOW()),
('CESIA', NOW(), NOW()),
('陽', NOW(), NOW()),
('しうた', NOW(), NOW()),
('hattori HNZ', NOW(), NOW()),
('Flying Fox', NOW(), NOW()),
('JAMLU7A', NOW(), NOW()),
('＃KTちゃん', NOW(), NOW()),
('SONOTA', NOW(), NOW()),
('テオくん（スカイピース）', NOW(), NOW()),
('FCザイロス', NOW(), NOW()),
('神', NOW(), NOW()),
('胡桃そら', NOW(), NOW()),
('L-指定', NOW(), NOW()),
('NAGASE', NOW(), NOW()),
('SHO', NOW(), NOW());

-- MC_RANKテーブルにデータを挿入
INSERT INTO `mc_rank` (`name`, `mcId`, `created_at`, `updated_at`)
SELECT 
    m.`name`,
    m.`id`,
    NOW(),
    NOW()
FROM `MC` m;

-- 外部キー制約を再度有効化
SET FOREIGN_KEY_CHECKS = 1; 